// <auto-generated />
using System;
using Libreria_PNT1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria_PNT1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124162327_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria_PNT1.Models.CategoriaEntity", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Nombre = "Ficción"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Nombre = "No Ficción"
                        });
                });

            modelBuilder.Entity("Libreria_PNT1.Models.ClienteEntity", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.HistorialPedidoEntity", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("HistorialPedidos");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.ItemPedidoEntity", b =>
                {
                    b.Property<int>("IdItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItemPedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdItemPedido");

                    b.HasIndex("IdLibro");

                    b.HasIndex("IdPedido");

                    b.ToTable("ItemsPedido");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.LibroEntity", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdLibro");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            IdLibro = 1,
                            Autor = "Cervantes",
                            CategoriaId = 1,
                            Descripcion = "Clásico",
                            Disponible = true,
                            Precio = 19999.99m,
                            Stock = 5,
                            Titulo = "El Quijote"
                        },
                        new
                        {
                            IdLibro = 2,
                            Autor = "Isaac Asimov",
                            CategoriaId = 1,
                            Descripcion = "Sci-Fi",
                            Disponible = true,
                            Precio = 15999.00m,
                            Stock = 3,
                            Titulo = "Fundación"
                        },
                        new
                        {
                            IdLibro = 3,
                            Autor = "JK Rowling",
                            CategoriaId = 1,
                            Descripcion = "Fantasia",
                            Disponible = true,
                            Precio = 16999.00m,
                            Stock = 7,
                            Titulo = "Harry Potter y la Piedra Filosofal"
                        },
                        new
                        {
                            IdLibro = 4,
                            Autor = "JK Rowling",
                            CategoriaId = 1,
                            Descripcion = "Fantasia",
                            Disponible = true,
                            Precio = 16999.00m,
                            Stock = 7,
                            Titulo = "Harry Potter y la Camara Secreta"
                        },
                        new
                        {
                            IdLibro = 5,
                            Autor = "JK Rowling",
                            CategoriaId = 1,
                            Descripcion = "Fantasia",
                            Disponible = true,
                            Precio = 16999.00m,
                            Stock = 7,
                            Titulo = "Harry Potter y el Prisionero de Azkaban"
                        },
                        new
                        {
                            IdLibro = 6,
                            Autor = "JK Rowling",
                            CategoriaId = 1,
                            Descripcion = "Fantasia",
                            Disponible = true,
                            Precio = 16999.00m,
                            Stock = 7,
                            Titulo = "Harry Potter y el Caliz de Fuego"
                        });
                });

            modelBuilder.Entity("Libreria_PNT1.Models.HistorialPedidoEntity", b =>
                {
                    b.HasOne("Libreria_PNT1.Models.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.ItemPedidoEntity", b =>
                {
                    b.HasOne("Libreria_PNT1.Models.LibroEntity", "Libro")
                        .WithMany()
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libreria_PNT1.Models.HistorialPedidoEntity", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.LibroEntity", b =>
                {
                    b.HasOne("Libreria_PNT1.Models.CategoriaEntity", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.CategoriaEntity", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Libreria_PNT1.Models.HistorialPedidoEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
