// <auto-generated />
using System;
using Libreria_PNT1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria_PNT1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110232748_Inicial_Libro")]
    partial class Inicial_Libro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria_PNT1.Models.LibroEntity", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Categoria")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdLibro");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            IdLibro = 1,
                            Autor = "Cervantes",
                            Descripcion = "Clásico",
                            Disponible = true,
                            Precio = 19999.99m,
                            Stock = 5,
                            Titulo = "El Quijote"
                        },
                        new
                        {
                            IdLibro = 2,
                            Autor = "Isaac Asimov",
                            Descripcion = "Sci-Fi",
                            Disponible = true,
                            Precio = 15999.00m,
                            Stock = 3,
                            Titulo = "Fundación"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
